<?php

// This file was autogenerated by the Jcodify, do not edit it directly

namespace Jcodify\Snazzyportfolio\Wordpress\ORM\Models\AutoGen\Models;

use Nzuridesigns\Worm\AbstractClasses\MetaModel;
use Nzuridesigns\Worm\Fields\OnetoManyACFField;
use Nzuridesigns\Worm\Fields\NonHierarchicalTaxonomyField;
use Jcodify\Snazzyportfolio\Wordpress\ORM\Models\Extended\ExtendedTimelinesMetaModel;
use Jcodify\Snazzyportfolio\Wordpress\ORM\Models\Extended\ExtendedprojectQueryModel;
use Nzuridesigns\Worm\AbstractClasses\Query;
use Jcodify\Snazzyportfolio\Wordpress\ORM\Models\Extended\ExtendedProjectMetaModel;
use Nzuridesigns\Worm\AbstractClasses\QueryType;

class ProjectMetaModel extends MetaModel
{
    public OnetoManyACFField $timelines;
    public NonHierarchicalTaxonomyField $taxonomyTechnology;

    public function __construct(int $id)
    {
        parent::__construct($id);
        $this->timelines = new OnetoManyACFField($id, 'otm-acf_timelines', ExtendedTimelinesMetaModel::class);
        $this->taxonomyTechnology = new NonHierarchicalTaxonomyField($id, 'technology');
    }
    public static function instance(MetaModel $model): static
    {
        if (!$model instanceof static) {
            throw new \Exception("Provided model is not an instance of ProjectMetaModel");
        }
        return $model;
    }

    public static function getQueries(): Query
    {
        $queries = new ExtendedprojectQueryModel();
        if ($queries instanceof Query) {
            return $queries;
        }
        throw new \Exception("Queries is not an instance of Query");
    }

    public static function filterByQueries(QueryType ...$querys): array
    {
        $items = self::getQueries()->filterByQueries(...$querys);
        return array_map(fn ($item) => new ExtendedProjectMetaModel($item->ID), $items);
    }

    public static function create($title = null, $publish = true): static
    {
        $metaModel = new ExtendedProjectMetaModel(self::createNewPost(self::getPostType(), $title, $publish));
        if ($metaModel instanceof MetaModel) {
            return $metaModel;
        }
        throw new \Exception("MetaModel is not an instance of MetaModel");
    }

    public static function getPostType(): string
    {
        return 'project';
    }
}
