<?php

// This file was autogenerated by the Jcodify, do not edit it directly

namespace Jcodify\Snazzyportfolio\Wordpress\ORM\Models\AutoGen\Models;

use Nzuridesigns\Worm\AbstractClasses\MetaModel;
use Nzuridesigns\Worm\Fields\BasicField;
use Nzuridesigns\Worm\Fields\NonHierarchicalTaxonomyField;
use Jcodify\Snazzyportfolio\Wordpress\ORM\Models\Extended\ExtendedTimelinesQueryModel;
use Nzuridesigns\Worm\AbstractClasses\Query;
use Jcodify\Snazzyportfolio\Wordpress\ORM\Models\Extended\ExtendedTimelinesMetaModel;
use Nzuridesigns\Worm\AbstractClasses\QueryType;

class TimelineMetaModel extends MetaModel
{
    public BasicField $startDate;
    public BasicField $endDate;
    public BasicField $institution;
    public BasicField $description;
    public BasicField $currentPlaceOfEmployment;
    public NonHierarchicalTaxonomyField $taxonomyPostTag;

    public function __construct(int $id)
    {
        parent::__construct($id);
        $this->startDate = new BasicField($id, 'start_date');
        $this->endDate = new BasicField($id, 'end_date');
        $this->institution = new BasicField($id, 'institution');
        $this->description = new BasicField($id, 'description');
        $this->currentPlaceOfEmployment = new BasicField($id, 'current_place_of_employment');
        $this->taxonomyPostTag = new NonHierarchicalTaxonomyField($id, 'post_tag');
    }
    public static function instance(MetaModel $model): static
    {
        if (!$model instanceof static) {
            throw new \Exception("Provided model is not an instance of TimelineMetaModel");
        }
        return $model;
    }

    public static function getQueries(): Query
    {
        $queries = new ExtendedTimelinesQueryModel();
        if ($queries instanceof Query) {
            return $queries;
        }
        throw new \Exception("Queries is not an instance of Query");
    }

    public static function filterByQueries(QueryType ...$querys): array
    {
        $items = self::getQueries()->filterByQueries(...$querys);
        return array_map(fn ($item) => new ExtendedTimelinesMetaModel($item->ID), $items);
    }

    public static function create($title = null, $publish = true): static
    {
        $metaModel = new ExtendedTimelinesMetaModel(self::createNewPost(self::getPostType(), $title, $publish));
        if ($metaModel instanceof MetaModel) {
            return $metaModel;
        }
        throw new \Exception("MetaModel is not an instance of MetaModel");
    }

    public static function getPostType(): string
    {
        return 'timeline';
    }

}
